# http routing section
[http]
  [http.routers]
    # Define a connection between requests and services
    [http.routers.express]
      rule = "PathPrefix(`/feedback`)"
      # If the rule matches, forward to the whoami service (declared below)
      service = "express-feedback"

  [http.services]
    # Define how to reach an existing service on our infrastructure
    [http.services.express-feedback.loadBalancer]
      [[http.services.express-feedback.loadBalancer.servers]]
        url = "http://192.168.100.4:3000/"