# http routing section
[http]
  [http.routers]
    # Define a connection between requests and services
    [http.routers.fp-feedback]
      entryPoints = ["web"]
      rule = "PathPrefix(`/feedback`)"
      service = "fp-feedback"

    [http.routers.fp-orders]
      entryPoints = ["web"]
      rule = "PathPrefix(`/api/v1/tea`)"
      service = "fp-orders"

  [http.services]
    # Define how to reach an existing service on our infrastructure
    [http.services.fp-feedback.loadBalancer]
      [[http.services.fp-feedback.loadBalancer.servers]]
        url = "http://172.17.0.1:3000/"

    [http.services.fp-orders.loadBalancer]
      [[http.services.fp-orders.loadBalancer.servers]]
        url = "http://172.17.0.1:10011/"